# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodl',
            name='Profile_pic',
            field=models.ImageField(default=None, upload_to=None),
            preserve_default=False,
        ),
    ]
