# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_registermodl_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodl',
            name='User_icon',
        ),
    ]
