# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_auto_20161108_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodl',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='registermodl',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='registermodl',
            name='Phone_number',
        ),
        migrations.RemoveField(
            model_name='registermodl',
            name='Suggestions',
        ),
        migrations.RemoveField(
            model_name='registermodl',
            name='Website',
        ),
    ]
