# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20161108_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='timelinemodl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.CharField(max_length=100)),
                ('Post_time', models.DateTimeField(auto_now_add=True)),
                ('Post_pic', models.FileField(blank=True, null=True, upload_to=b'')),
                ('PostNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.registermodl')),
            ],
        ),
    ]
