# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0009_friendmodl'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodl',
            name='account_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
